In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import numpy as np
from sklearn.metrics import accuracy_score 

In [2]:
%cd Desktop

C:\Users\VIJESH\Desktop


In [3]:
df = pd.read_csv('parity5_plus_5.csv')

In [4]:
df.head()

Bit_1  Bit_2  Bit_3  Bit_4  Bit_5  Bit_6  Bit_7  Bit_8  Bit_9  Bit_10  \
0      1      1      0      0      1      0      0      0      0       1   
1      1      0      0      0      0      1      1      1      1       0   
2      0      0      1      0      1      1      1      1      1       1   
3      0      1      0      1      0      0      0      1      0       0   
4      0      0      0      0      0      0      0      1      1       0   

   class  
0      1  
1      0  
2      1  
3      1  
4      1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1124 entries, 0 to 1123
Data columns (total 11 columns):
Bit_1     1124 non-null int64
Bit_2     1124 non-null int64
Bit_3     1124 non-null int64
Bit_4     1124 non-null int64
Bit_5     1124 non-null int64
Bit_6     1124 non-null int64
Bit_7     1124 non-null int64
Bit_8     1124 non-null int64
Bit_9     1124 non-null int64
Bit_10    1124 non-null int64
class     1124 non-null int64
dtypes: int64(11)
memory usage: 96.7 KB


In [6]:
df.describe()  # all are catogorical data

Bit_1        Bit_2        Bit_3        Bit_4        Bit_5  \
count  1124.000000  1124.000000  1124.000000  1124.000000  1124.000000   
mean      0.489324     0.491103     0.501779     0.500890     0.494662   
std       0.500109     0.500143     0.500219     0.500222     0.500194   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     1.000000     1.000000     0.000000   
75%       1.000000     1.000000     1.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

             Bit_6        Bit_7        Bit_8        Bit_9       Bit_10  \
count  1124.000000  1124.000000  1124.000000  1124.000000  1124.000000   
mean      0.496441     0.500000     0.496441     0.503559     0.486655   
std       0.500210     0.500223     0.500210     0.500210     0.500044   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.500000     0.000000     1.000000     0.000000   
75%       1.000000     1.000000     1.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

             class  
count  1124.000000  
mean      0.504448  
std       0.500203  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

In [7]:
x=df.drop(columns='class') #takes all features except target variable as 'x'
y=df['class'].copy()       #takes the target feature as 'y'


x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2) #spliting the data

## Logistic Regression

In [8]:
lr = LogisticRegression()
lr.fit(x_train, y_train) #training the model

y_pred = lr.predict(x_test) #evaluating with the test data

c_m=confusion_matrix(y_test, y_pred) #confusion matrix

score =accuracy_score(y_test,y_pred)
print(score*100)
c_m

44.888888888888886


C:\Users\VIJESH\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([[25, 96],
       [28, 76]], dtype=int64)

In [9]:
Total=c_m[0,1]+c_m[1,0]+c_m[0,0]+c_m[1,1]
FP=(c_m[1,0]/Total)*100
FN=(c_m[0,1]/Total)*100
print("FP =",FP)#False positive
print("FN =",FN)# False Negative

FP = 12.444444444444445
FN = 42.66666666666667


## Neural Network-1

In [10]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score 


model = MLPClassifier(hidden_layer_sizes=(10,50)) #2 layer

model.fit(x_train, y_train) #training the model

predicted_classes = model.predict(x_test) #evaluating with test data


accuracy = accuracy_score(y_test,predicted_classes)
print(accuracy)


0.9822222222222222


C:\Users\VIJESH\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [11]:
c_m=confusion_matrix(y_test,predicted_classes ) #confusion matrix of NN-1
c_m

array([[118,   3],
       [  1, 103]], dtype=int64)

In [12]:
Total=c_m[0,1]+c_m[1,0]+c_m[0,0]+c_m[1,1]
FP=(c_m[1,0]/Total)*100
FN=(c_m[0,1]/Total)*100
print("FP =",FP)#False positive
print("FN =",FN)# False Negative

FP = 0.4444444444444444
FN = 1.3333333333333335


## Neural Network -2

In [13]:
model = MLPClassifier(hidden_layer_sizes=(5,20,30)) #3 layer

model.fit(x_train, y_train)
predicted_classes = model.predict(x_test)
accuracy = accuracy_score(y_test,predicted_classes)
print(accuracy)
c_m=confusion_matrix(y_test,predicted_classes )
c_m

0.96


C:\Users\VIJESH\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


array([[121,   0],
       [  9,  95]], dtype=int64)

In [14]:
Total=c_m[0,1]+c_m[1,0]+c_m[0,0]+c_m[1,1]
FP=(c_m[1,0]/Total)*100
FN=(c_m[0,1]/Total)*100
print("FP =",FP) # False positive
print("FN =",FN)# False Negative

FP = 4.0
FN = 0.0


## Neural Network - 3

In [15]:
model = MLPClassifier(hidden_layer_sizes=(5,10,30,40,50,60,70)) #7 layer

model.fit(x_train, y_train)
predicted_classes = model.predict(x_test)
accuracy = accuracy_score(y_test,predicted_classes)
print(accuracy)
c_m=confusion_matrix(y_test,predicted_classes )
c_m

1.0


array([[121,   0],
       [  0, 104]], dtype=int64)

In [16]:
Total=c_m[0,1]+c_m[1,0]+c_m[0,0]+c_m[1,1]
FP=(c_m[1,0]/Total)*100
FN=(c_m[0,1]/Total)*100
print("FP =",FP)#False positive
print("FN =",FN)# False Negative

FP = 0.0
FN = 0.0
